version: "3.1"

services:
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - 8000:8000
  #   command: ["python", "main.py"]
  #   depends_on:
  #     - postgresql
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
