version: "3.1"

services:
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
